/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>

#define RCC_Base 0x40021000
#define GPIOPA_Base 0x40010800

typedef volatile unsigned int vuint32_t; 

#define RCC_APB2ENR (*(vuint32_t *)(RCC_Base + 0x18))
#define GPIOPA_CRH  (*(vuint32_t *)(GPIOPA_Base + 0x04))
#define GPIOPA_ODR (*(vuint32_t *)(GPIOPA_Base + 0x0c))

typedef union {
	vuint32_t all_fields;
	struct {
		vuint32_t reserved:13;
		vuint32_t P_13:1;
	} Pin;
} ODR_t;

volatile ODR_t* output_ODR = (volatile ODR_t*)(GPIOPA_Base+0x0c);
volatile unsigned int Unintialized_Global;
unsigned char G_variables[] = {1,2,3};

int main(void)
{
    RCC_APB2ENR |= 1<<2;
    GPIOPA_CRH &= 0xff0ffff;
    GPIOPA_CRH |= 0x00200000;
    while (1) {
    	output_ODR->Pin.P_13 = 1;
    	for(int i=0;i<5000;i++);
    	output_ODR->Pin.P_13 = 0;
    	for(int i=0;i<5000;i++);
    }
     return 0;
}
